[rotor_i]
input = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z'
]
output = [
    'e',
    'k',
    'm',
    'f',
    'l',
    'g',
    'd',
    'q',
    'v',
    'z',
    'n',
    't',
    'o',
    'w',
    'y',
    'h',
    'x',
    'u',
    's',
    'p',
    'a',
    'i',
    'b',
    'r',
    'c',
    'j'
]

[rotor_ii]
input = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z'
]
output = [
    'a',
    'j',
    'd',
    'k',
    's',
    'i',
    'r',
    'u',
    'x',
    'b',
    'l',
    'h',
    'w',
    't',
    'm',
    'c',
    'q',
    'g',
    'z',
    'n',
    'p',
    'y',
    'f',
    'v',
    'o',
    'e'
]


[rotor_iii]
input = [
    'a',
    'b',
    'c',
    'd',
    'e',
    'f',
    'g',
    'h',
    'i',
    'j',
    'k',
    'l',
    'm',
    'n',
    'o',
    'p',
    'q',
    'r',
    's',
    't',
    'u',
    'v',
    'w',
    'x',
    'y',
    'z'
]
output = [
    'b',
    'd',
    'f',
    'h',
    'j',
    'l',
    'c',
    'p',
    'r',
    't',
    'x',
    'v',
    'z',
    'n',
    'y',
    'e',
    'i',
    'w',
    'g',
    'a',
    'k',
    'm',
    'u',
    's',
    'q',
    'o'
]
